spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/sfp
    platform: postgres
    username: postgres
    password: postgres
  data:
    mongodb:
      port: 27017
      database: sfp
      host: localhost
      uri: mongodb://localhost:27017/sfp
  servlet:
    multipart:
      max-file-size: 20MB
      file-size-threshold: 20MB
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: sfp
  mail:
    host: smtp.gmail.com
    port: 587
    username: slava.vb.bondarchuk@gmail.com
    password: 050698$$
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
server:
  undertow:
    io-threads: 4
    worker-threads: 4
  port: 9090
mail:
  settings:
    from: sfp-storage.com
  activations:
    address: localhost:8080/sfp/api/users/activate/